"""INIT DBs

Revision ID: 3d6f479e84d7
Revises: 9e5260026980
Create Date: 2023-01-03 23:30:26.360915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6f479e84d7'
down_revision = '9e5260026980'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('i_have_it', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'i_have_it')
    # ### end Alembic commands ###
